<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.navercorp.pinpoint</groupId>
        <artifactId>pinpoint</artifactId>
        <version>2.5.3</version>
    </parent>

    <artifactId>pinpoint-commons</artifactId>
    <name>pinpoint-commons</name>
    <packaging>jar</packaging>

    <dependencies>

        <!-- Logging dependencies -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <scope>test</scope>
        </dependency>


        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.gmaven</groupId>
                <artifactId>gmaven-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                        <configuration>
                            <source>${pom.basedir}/VersionScript.groovy</source>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <transformers>
                        <!-- 合并META-INF/services下的文件 -->
                        <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                    </transformers>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
                                <relocation>
                                    <pattern>com</pattern>
                                    <shadedPattern>graalvm.image.com</shadedPattern>
                                    <excludes>
                                        <exclude>com.navercorp.**</exclude>
                                    </excludes>
                                </relocation>
                                <relocation>
                                    <pattern>io</pattern>
                                    <shadedPattern>graalvm.image.io</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>android</pattern>
                                    <shadedPattern>graalvm.image.android</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org</pattern>
                                    <shadedPattern>graalvm.image.org</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>google</pattern>
                                    <shadedPattern>graalvm.image.google</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>javax</pattern>
                                    <shadedPattern>graalvm.image.javax</shadedPattern>
                                    <excludes>
                                        <exclude>javax.management.**</exclude>
                                        <exclude>javax.crypto.**</exclude>
                                        <exclude>javax.net.**</exclude>
                                        <exclude>javax.security.**</exclude>
                                    </excludes>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
