<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.navercorp.pinpoint</groupId>
        <artifactId>pinpoint</artifactId>
        <relativePath>../../pom.xml</relativePath>
        <version>2.5.3</version>
    </parent>

    <artifactId>pinpoint-agent-proxy-common</artifactId>
    <name>pinpoint-agent-proxy-common</name>
    <packaging>jar</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <transformers>
                        <!-- 合并META-INF/services下的文件 -->
                        <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                    </transformers>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <relocations>
                                <relocation>
                                    <pattern>com</pattern>
                                    <shadedPattern>graalvm.image.com</shadedPattern>
                                    <excludes>
                                        <exclude>com.navercorp.**</exclude>
                                    </excludes>
                                </relocation>
                                <relocation>
                                    <pattern>io</pattern>
                                    <shadedPattern>graalvm.image.io</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>android</pattern>
                                    <shadedPattern>graalvm.image.android</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org</pattern>
                                    <shadedPattern>graalvm.image.org</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>google</pattern>
                                    <shadedPattern>graalvm.image.google</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>javax</pattern>
                                    <shadedPattern>graalvm.image.javax</shadedPattern>
                                    <excludes>
                                        <exclude>javax.management.**</exclude>
                                        <exclude>javax.crypto.**</exclude>
                                        <exclude>javax.net.**</exclude>
                                        <exclude>javax.security.**</exclude>
                                    </excludes>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>